### ISSUE TITLE
Práctica de Animación

### ISSUE THREAD

**Issue by Anthony4523** [SistemasTecTlaxiaco/practica-de-objeto-3d-en-blender-con-animacion-equipo_prestadores-de-servicios#1]
[Práctica 4_Animación de objetos 3D.pdf](https://github.com/SistemasTecTlaxiaco/practica-de-objeto-3d-en-blender-con-animacion-equipo_prestadores-de-servicios/files/8348232/Practica.4_Animacion.de.objetos.3D.pdf)

**Comment by Nancy2050** [comment]
Puntos 20/20

**Comment by josealfredo79** [comment]
bien hecho y revisado
